In [1]:
%load_ext sql

In [2]:
%sql ibm_db_sa://qmm86575:b1t%2Bqf9vsl0h444j@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB

'Connected: qmm86575@BLUDB'

In [3]:
%sql SELECT * FROM SYSCAT.TABLES WHERE TABNAME = 'SCHOOLS'

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('QMM86575', 'SCHOOLS', 'QMM86575', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2020, 7, 9, 17, 3, 57, 459856), datetime.datetime(2020, 7, 9, 17, 3, 57, 459856), datetime.datetime(2020, 7, 9, 17, 3, 57, 459856), datetime.datetime(2020, 7, 9, 17, 5, 42, 257614), 78, 7, 1984, 566, 15, 0, 16, -1, -1, -1, 0, 'qmm86575space1', None, None, 0, 0, 0, 0, 0, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 844, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2020, 7, 9, 17, 3, 57, 459856), 0, ' ', None, None, 'N', 'QMM86575', ' ', ' ', ' ', datetime.date(2020, 7, 9), ' ', 'N', 'R', 'N', -1.0, None)]

In [4]:
%sql SELECT COUNT(*) FROM SYSCAT.COLUMNS WHERE TABNAME = 'SCHOOLS'

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('78'),)]

In [5]:
%sql SELECT TYPENAME, COLNAME, LENGTH FROM SYSCAT.COLUMNS WHERE TABNAME = 'SCHOOLS'

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('INTEGER', 'School_ID', 4),
 ('VARCHAR', 'NAME_OF_SCHOOL', 65),
 ('VARCHAR', 'Elementary, Middle, or High School', 2),
 ('VARCHAR', 'Street_Address', 30),
 ('VARCHAR', 'City', 7),
 ('VARCHAR', 'State', 2),
 ('INTEGER', 'ZIP_Code', 4),
 ('VARCHAR', 'Phone_Number', 14),
 ('VARCHAR', 'Link', 78),
 ('VARCHAR', 'Network_Manager', 40),
 ('VARCHAR', 'Collaborative_Name', 34),
 ('VARCHAR', 'Adequate_Yearly_Progress_Made_', 3),
 ('VARCHAR', 'Track_Schedule', 12),
 ('VARCHAR', 'CPS_Performance_Policy_Status', 16),
 ('VARCHAR', 'CPS_Performance_Policy_Level', 15),
 ('VARCHAR', 'HEALTHY_SCHOOL_CERTIFIED', 3),
 ('VARCHAR', 'Safety_Icon', 11),
 ('SMALLINT', 'SAFETY_SCORE', 2),
 ('VARCHAR', 'Family_Involvement_Icon', 11),
 ('VARCHAR', 'Family_Involvement_Score', 3),
 ('VARCHAR', 'Environment_Icon', 11),
 ('SMALLINT', 'Environment_Score', 2),
 ('VARCHAR', 'Instruction_Icon', 11),
 ('SMALLINT', 'Instruction_Score', 2),
 ('VARCHAR', 'Leaders_Icon', 11),
 ('VARCHAR', 'Leaders_Score', 3),
 ('VARCHAR', 'Teachers_Icon', 11),
 ('VARCHAR', 'Teachers_Score', 3),
 ('VARCHAR', 'Parent_Engagement_Icon', 7),
 ('VARCHAR', 'Parent_Engagement_Score', 3),
 ('VARCHAR', 'Parent_Environment_Icon', 7),
 ('VARCHAR', 'Parent_Environment_Score', 3),
 ('VARCHAR', 'AVERAGE_STUDENT_ATTENDANCE', 6),
 ('DECIMAL', 'Rate_of_Misconducts__per_100_students_', 5),
 ('VARCHAR', 'Average_Teacher_Attendance', 6),
 ('VARCHAR', 'Individualized_Education_Program_Compliance_Rate', 7),
 ('VARCHAR', 'Pk_2_Literacy__', 4),
 ('VARCHAR', 'Pk_2_Math__', 4),
 ('VARCHAR', 'Gr3_5_Grade_Level_Math__', 4),
 ('VARCHAR', 'Gr3_5_Grade_Level_Read__', 4),
 ('VARCHAR', 'Gr3_5_Keep_Pace_Read__', 4),
 ('VARCHAR', 'Gr3_5_Keep_Pace_Math__', 4),
 ('VARCHAR', 'Gr6_8_Grade_Level_Math__', 4),
 ('VARCHAR', 'Gr6_8_Grade_Level_Read__', 4),
 ('VARCHAR', 'Gr6_8_Keep_Pace_Math_', 4),
 ('VARCHAR', 'Gr6_8_Keep_Pace_Read__', 4),
 ('VARCHAR', 'Gr_8_Explore_Math__', 4),
 ('VARCHAR', 'Gr_8_Explore_Read__', 4),
 ('DECIMAL', 'ISAT_Exceeding_Math__', 4),
 ('DECIMAL', 'ISAT_Exceeding_Reading__', 4),
 ('DECIMAL', 'ISAT_Value_Add_Math', 3),
 ('DECIMAL', 'ISAT_Value_Add_Read', 3),
 ('VARCHAR', 'ISAT_Value_Add_Color_Math', 6),
 ('VARCHAR', 'ISAT_Value_Add_Color_Read', 6),
 ('VARCHAR', 'Students_Taking__Algebra__', 4),
 ('VARCHAR', 'Students_Passing__Algebra__', 4),
 ('VARCHAR', '9th Grade EXPLORE (2009)', 4),
 ('VARCHAR', '9th Grade EXPLORE (2010)', 4),
 ('VARCHAR', '10th Grade PLAN (2009)', 4),
 ('VARCHAR', '10th Grade PLAN (2010)', 4),
 ('VARCHAR', 'Net_Change_EXPLORE_and_PLAN', 3),
 ('VARCHAR', '11th Grade Average ACT (2011)', 4),
 ('VARCHAR', 'Net_Change_PLAN_and_ACT', 3),
 ('VARCHAR', 'College_Eligibility__', 4),
 ('VARCHAR', 'Graduation_Rate__', 4),
 ('VARCHAR', 'College_Enrollment_Rate__', 4),
 ('SMALLINT', 'COLLEGE_ENROLLMENT', 2),
 ('SMALLINT', 'General_Services_Route', 2),
 ('VARCHAR', 'Freshman_on_Track_Rate__', 4),
 ('DECIMAL', 'X_COORDINATE', 13),
 ('DECIMAL', 'Y_COORDINATE', 13),
 ('DECIMAL', 'Latitude', 18),
 ('DECIMAL', 'Longitude', 18),
 ('SMALLINT', 'COMMUNITY_AREA_NUMBER', 2),
 ('VARCHAR', 'COMMUNITY_AREA_NAME', 22),
 ('SMALLINT', 'Ward', 2),
 ('SMALLINT', 'Police_District', 2),
 ('VARCHAR', 'Location', 27)]

In [6]:
%sql SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME = 'SCHOOLS'

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('QMM86575', 'SCHOOLS', 'School_ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 566, '610543', '609674', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'NAME_OF_SCHOOL', 1, 'SYSIBM  ', 'VARCHAR', 65, 0, 'OCTETS', 65, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'Woodlawn Community Elementary Sch'", "'Abraham Lincoln Elementary School'", 41, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 36, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Elementary, Middle, or High School', 2, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'MS'", "'ES'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Street_Address', 3, 'SYSIBM  ', 'VARCHAR', 30, 0, 'OCTETS', 30, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'9912 S Avenue H'", "'10015 S Leavitt St'", 22, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 17, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'City', 4, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 1, "'Chicago'", "'Chicago'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'State', 5, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 1, "'IL'", "'IL'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ZIP_Code', 6, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 51, '60707', '60607', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Phone_Number', 7, 'SYSIBM  ', 'VARCHAR', 14, 0, 'OCTETS', 14, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'(773) 535-9930'", "'(773) 534-0146'", 19, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 14, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Link', 8, 'SYSIBM  ', 'VARCHAR', 78, 0, 'OCTETS', 78, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "''", "'http://schoolreports.cps.edu/Scho'", 83, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 78, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Network_Manager', 9, 'SYSIBM  ', 'VARCHAR', 40, 0, 'OCTETS', 40, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 20, "'Southwest Side High School Networ'", "'Austin-North Lawndale Elementary '", 35, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 30, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Collaborative_Name', 10, 'SYSIBM  ', 'VARCHAR', 34, 0, 'OCTETS', 34, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 5, "'SOUTHWEST SIDE COLLABORATIVE'", "'NORTH-NORTHWEST SIDE COLLABORATIV'", 33, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 28, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Adequate_Yearly_Progress_Made_', 11, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'Yes'", "'NDA'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Track_Schedule', 12, 'SYSIBM  ', 'VARCHAR', 12, 0, 'OCTETS', 12, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'Track_E'", "'Non_Standard'", 13, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 8, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'CPS_Performance_Policy_Status', 13, 'SYSIBM  ', 'VARCHAR', 16, 0, 'OCTETS', 16, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Not on Probation'", "'Not Applicable'", 18, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 13, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'CPS_Performance_Policy_Level', 14, 'SYSIBM  ', 'VARCHAR', 15, 0, 'OCTETS', 15, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 5, "'NDA'", "'Level 2'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'HEALTHY_SCHOOL_CERTIFIED', 15, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "'Yes'", "'No'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Safety_Icon', 16, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'SAFETY_SCORE', 17, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 86, '99', '5', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Family_Involvement_Icon', 18, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Family_Involvement_Score', 19, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 72, "'99'", "'17'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Environment_Icon', 20, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Environment_Score', 21, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 80, '99', '2', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Instruction_Icon', 22, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Instruction_Score', 23, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 83, '99', '11', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Leaders_Icon', 24, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Leaders_Score', 25, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 79, "'99'", "'14'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Teachers_Icon', 26, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Teachers_Score', 27, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 77, "'99'", "'14'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Parent_Engagement_Icon', 28, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Strong'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Parent_Engagement_Score', 29, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 32, "'69'", "'39'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Parent_Environment_Icon', 30, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Strong'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Parent_Environment_Score', 31, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 33, "'70'", "'36'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'AVERAGE_STUDENT_ATTENDANCE', 32, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 155, "'98.40%'", "'60.90%'", 11, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Rate_of_Misconducts__per_100_students_', 33, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 288, '+0230.6', '+0000.1', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Average_Teacher_Attendance', 34, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 55, "'98.10%'", "'91.70%'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Individualized_Education_Program_Compliance_Rate', 35, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 69, "'99.60%'", "'72.70%'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Pk_2_Literacy__', 36, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 308, "'96.3'", "'16.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Pk_2_Math__', 37, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 224, "'97.2'", "'10.1'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr3_5_Grade_Level_Math__', 38, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 336, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr3_5_Grade_Level_Read__', 39, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 340, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr3_5_Keep_Pace_Read__', 40, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 276, "'82.5'", "'28.8'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr3_5_Keep_Pace_Math__', 41, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'83.5'", "'21.7'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr6_8_Grade_Level_Math__', 42, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 296, "'96.5'", "'10.2'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr6_8_Grade_Level_Read__', 43, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 300, "'98.9'", "'100'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr6_8_Keep_Pace_Math_', 44, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 268, "'93.6'", "'24.3'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr6_8_Keep_Pace_Read__', 45, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'85.5'", "'21.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr_8_Explore_Math__', 46, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 208, "'9.7'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr_8_Explore_Read__', 47, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 244, "'99'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Exceeding_Math__', 48, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 297, '+100.0', '+000.6', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Exceeding_Reading__', 49, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 261, '+100.0', '+000.5', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Value_Add_Math', 50, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 57, '+03.6', '-03.1', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Value_Add_Read', 51, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 60, '+04.9', '-02.8', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Value_Add_Color_Math', 52, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Red'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Value_Add_Color_Read', 53, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Red'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),

In [7]:
##%sql SELECT * FROM SCHOOLS

In [8]:
%sql SELECT COUNT(*) FROM SCHOOLS WHERE "Elementary, Middle, or High School" = 'ES'

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('462'),)]

In [9]:
%sql SELECT MAX(SAFETY_SCORE) FROM SCHOOLS

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(99,)]

In [10]:
%sql SELECT NAME_OF_SCHOOL, SAFETY_SCORE FROM SCHOOLS WHERE SAFETY_SCORE = (SELECT MAX(SAFETY_SCORE) FROM SCHOOLS)

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Abraham Lincoln Elementary School', 99),
 ('Alexander Graham Bell Elementary School', 99),
 ('Annie Keller Elementary Gifted Magnet School', 99),
 ('Augustus H Burley Elementary School', 99),
 ('Edgar Allan Poe Elementary Classical School', 99),
 ('Edgebrook Elementary School', 99),
 ('Ellen Mitchell Elementary School', 99),
 ('James E McDade Elementary Classical School', 99),
 ('James G Blaine Elementary School', 99),
 ('LaSalle Elementary Language Academy', 99),
 ('Mary E Courtenay Elementary Language Arts Center', 99),
 ('Northside College Preparatory High School', 99),
 ('Northside Learning Center High School', 99),
 ('Norwood Park Elementary School', 99),
 ('Oriole Park Elementary School', 99),
 ('Sauganash Elementary School', 99),
 ('Stephen Decatur Classical Elementary School', 99),
 ('Talman Elementary School', 99),
 ('Wildwood Elementary School', 99)]

In [11]:
%sql SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME = 'SCHOOLS'

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('QMM86575', 'SCHOOLS', 'School_ID', 0, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 566, '610543', '609674', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'NAME_OF_SCHOOL', 1, 'SYSIBM  ', 'VARCHAR', 65, 0, 'OCTETS', 65, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'Woodlawn Community Elementary Sch'", "'Abraham Lincoln Elementary School'", 41, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 36, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Elementary, Middle, or High School', 2, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'MS'", "'ES'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Street_Address', 3, 'SYSIBM  ', 'VARCHAR', 30, 0, 'OCTETS', 30, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'9912 S Avenue H'", "'10015 S Leavitt St'", 22, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 17, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'City', 4, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 1, "'Chicago'", "'Chicago'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'State', 5, 'SYSIBM  ', 'VARCHAR', 2, 0, 'OCTETS', 2, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 1, "'IL'", "'IL'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ZIP_Code', 6, 'SYSIBM  ', 'INTEGER', 4, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 51, '60707', '60607', 5, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Phone_Number', 7, 'SYSIBM  ', 'VARCHAR', 14, 0, 'OCTETS', 14, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 566, "'(773) 535-9930'", "'(773) 534-0146'", 19, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 14, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Link', 8, 'SYSIBM  ', 'VARCHAR', 78, 0, 'OCTETS', 78, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "''", "'http://schoolreports.cps.edu/Scho'", 83, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 78, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Network_Manager', 9, 'SYSIBM  ', 'VARCHAR', 40, 0, 'OCTETS', 40, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 20, "'Southwest Side High School Networ'", "'Austin-North Lawndale Elementary '", 35, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 30, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Collaborative_Name', 10, 'SYSIBM  ', 'VARCHAR', 34, 0, 'OCTETS', 34, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 5, "'SOUTHWEST SIDE COLLABORATIVE'", "'NORTH-NORTHWEST SIDE COLLABORATIV'", 33, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 28, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Adequate_Yearly_Progress_Made_', 11, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'Yes'", "'NDA'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Track_Schedule', 12, 'SYSIBM  ', 'VARCHAR', 12, 0, 'OCTETS', 12, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 3, "'Track_E'", "'Non_Standard'", 13, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 8, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'CPS_Performance_Policy_Status', 13, 'SYSIBM  ', 'VARCHAR', 16, 0, 'OCTETS', 16, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Not on Probation'", "'Not Applicable'", 18, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 13, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'CPS_Performance_Policy_Level', 14, 'SYSIBM  ', 'VARCHAR', 15, 0, 'OCTETS', 15, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 5, "'NDA'", "'Level 2'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'HEALTHY_SCHOOL_CERTIFIED', 15, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 2, "'Yes'", "'No'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Safety_Icon', 16, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'SAFETY_SCORE', 17, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 86, '99', '5', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Family_Involvement_Icon', 18, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Family_Involvement_Score', 19, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 72, "'99'", "'17'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Environment_Icon', 20, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Environment_Score', 21, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 80, '99', '2', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Instruction_Icon', 22, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Instruction_Score', 23, 'SYSIBM  ', 'SMALLINT', 2, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 83, '99', '11', 3, None, 0, 20, 10, 53, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Leaders_Icon', 24, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Leaders_Score', 25, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 79, "'99'", "'14'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Teachers_Icon', 26, 'SYSIBM  ', 'VARCHAR', 11, 0, 'OCTETS', 11, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 6, "'Very Weak'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Teachers_Score', 27, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 77, "'99'", "'14'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Parent_Engagement_Icon', 28, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Strong'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Parent_Engagement_Score', 29, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 32, "'69'", "'39'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Parent_Environment_Icon', 30, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Strong'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Parent_Environment_Score', 31, 'SYSIBM  ', 'VARCHAR', 3, 0, 'OCTETS', 3, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 33, "'70'", "'36'", 7, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 2, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'AVERAGE_STUDENT_ATTENDANCE', 32, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 155, "'98.40%'", "'60.90%'", 11, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Rate_of_Misconducts__per_100_students_', 33, 'SYSIBM  ', 'DECIMAL', 5, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 288, '+0230.6', '+0000.1', 4, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Average_Teacher_Attendance', 34, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 55, "'98.10%'", "'91.70%'", 11, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 6, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Individualized_Education_Program_Compliance_Rate', 35, 'SYSIBM  ', 'VARCHAR', 7, 0, 'OCTETS', 7, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 69, "'99.60%'", "'72.70%'", 12, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 7, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Pk_2_Literacy__', 36, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 308, "'96.3'", "'16.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Pk_2_Math__', 37, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 224, "'97.2'", "'10.1'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr3_5_Grade_Level_Math__', 38, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 336, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr3_5_Grade_Level_Read__', 39, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 340, "'98.6'", "'10'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr3_5_Keep_Pace_Read__', 40, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 276, "'82.5'", "'28.8'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr3_5_Keep_Pace_Math__', 41, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'83.5'", "'21.7'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr6_8_Grade_Level_Math__', 42, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 296, "'96.5'", "'10.2'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr6_8_Grade_Level_Read__', 43, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 300, "'98.9'", "'100'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr6_8_Keep_Pace_Math_', 44, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 268, "'93.6'", "'24.3'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr6_8_Keep_Pace_Read__', 45, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 260, "'85.5'", "'21.4'", 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 4, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr_8_Explore_Math__', 46, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 208, "'9.7'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'Gr_8_Explore_Read__', 47, 'SYSIBM  ', 'VARCHAR', 4, 0, 'OCTETS', 4, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 244, "'99'", "'1.4'", 8, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 3, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Exceeding_Math__', 48, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 297, '+100.0', '+000.6', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Exceeding_Reading__', 49, 'SYSIBM  ', 'DECIMAL', 4, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 261, '+100.0', '+000.5', 4, None, 0, 20, 10, 90, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Value_Add_Math', 50, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 57, '+03.6', '-03.1', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Value_Add_Read', 51, 'SYSIBM  ', 'DECIMAL', 3, 1, None, None, None, 'Y', 0, None, None, ' ', ' ', 60, '+04.9', '-02.8', 3, None, 0, 20, 10, 98, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Value_Add_Color_Math', 52, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Red'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'SCHOOLS', 'ISAT_Value_Add_Color_Read', 53, 'SYSIBM  ', 'VARCHAR', 6, 0, 'OCTETS', 6, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', ' ', ' ', 4, "'Red'", "'NDA'", 10, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, 5, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),

In [12]:
%sql select Name_of_School, Average_Student_Attendance from SCHOOLS \
    order by Average_Student_Attendance desc nulls last limit 10

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('John Charles Haines Elementary School', '98.40%'),
 ('James Ward Elementary School', '97.80%'),
 ('Edgar Allan Poe Elementary Classical School', '97.60%'),
 ('Orozco Fine Arts & Sciences Elementary School', '97.60%'),
 ('Rachel Carson Elementary School', '97.60%'),
 ('Annie Keller Elementary Gifted Magnet School', '97.50%'),
 ('Andrew Jackson Elementary Language Academy', '97.40%'),
 ('Lenart Elementary Regional Gifted Center', '97.40%'),
 ('Disney II Magnet School', '97.30%'),
 ('John H Vanderpoel Elementary Magnet School', '97.20%')]

In [13]:
%sql select Name_of_School, Average_Student_Attendance from SCHOOLS \
    order by Average_Student_Attendance \
    fetch first 5 rows only

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%')]

In [14]:
%sql select Name_of_School, REPLACE(Average_Student_Attendance, '%', '') as Average_Student_Attendance from SCHOOLS \
    order by Average_Student_Attendance \
    fetch first 5 rows only

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Richard T Crane Technical Preparatory High School', '57.90'),
 ('Barbara Vick Early Childhood & Family Center', '60.90'),
 ('Dyett High School', '62.50'),
 ('Wendell Phillips Academy High School', '63.00'),
 ('Orr Academy High School', '66.30')]

In [15]:
%sql select Name_of_School, Average_Student_Attendance from SCHOOLS \
    WHERE CAST(REPLACE(Average_Student_Attendance, '%', '') as DOUBLE) < 70 \
    order by Average_Student_Attendance

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%'),
 ('Manley Career Academy High School', '66.80%'),
 ('Chicago Vocational Career Academy High School', '68.80%'),
 ('Roberto Clemente Community Academy High School', '69.60%')]

In [16]:
%sql SELECT Name_of_School, Average_Student_Attendance  \
     from SCHOOLS \
     where CAST ( REPLACE(Average_Student_Attendance, '%', '') AS DOUBLE ) < 70 \
     order by Average_Student_Attendance

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('Richard T Crane Technical Preparatory High School', '57.90%'),
 ('Barbara Vick Early Childhood & Family Center', '60.90%'),
 ('Dyett High School', '62.50%'),
 ('Wendell Phillips Academy High School', '63.00%'),
 ('Orr Academy High School', '66.30%'),
 ('Manley Career Academy High School', '66.80%'),
 ('Chicago Vocational Career Academy High School', '68.80%'),
 ('Roberto Clemente Community Academy High School', '69.60%')]

In [17]:
%sql SELECT COMMUNITY_AREA_NAME, SUM(COLLEGE_ENROLLMENT) as COLLEGE_ENROLLMENT \
    FROM SCHOOLS \
    GROUP BY COMMUNITY_AREA_NAME

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('ALBANY PARK', 6864),
 ('ARCHER HEIGHTS', 4823),
 ('ARMOUR SQUARE', 1458),
 ('ASHBURN', 6483),
 ('AUBURN GRESHAM', 4175),
 ('AUSTIN', 10933),
 ('AVALON PARK', 1522),
 ('AVONDALE', 3640),
 ('BELMONT CRAGIN', 14386),
 ('BEVERLY', 1636),
 ('BRIDGEPORT', 3167),
 ('BRIGHTON PARK', 9647),
 ('BURNSIDE', 549),
 ('CALUMET HEIGHTS', 1568),
 ('CHATHAM', 5042),
 ('CHICAGO LAWN', 7086),
 ('CLEARING', 2085),
 ('DOUGLAS', 4670),
 ('DUNNING', 4568),
 ('EAST GARFIELD PARK', 5337),
 ('EAST SIDE', 5305),
 ('EDGEWATER', 4600),
 ('EDISON PARK', 910),
 ('ENGLEWOOD', 6832),
 ('FOREST GLEN', 1431),
 ('FULLER PARK', 531),
 ('GAGE PARK', 9915),
 ('GARFIELD RIDGE', 4552),
 ('GRAND BOULEVARD', 2809),
 ('GREATER GRAND CROSSING', 4051),
 ('HEGEWISCH', 963),
 ('HERMOSA', 3975),
 ('HUMBOLDT PARK', 8620),
 ('HYDE PARK', 1930),
 ('IRVING PARK', 7764),
 ('JEFFERSON PARK', 1755),
 ('KENWOOD', 4287),
 ('LAKE VIEW', 7055),
 ('LINCOLN PARK', 5615),
 ('LINCOLN SQUARE', 4132),
 ('LOGAN SQUARE', 7351),
 ('LOOP', 871),
 ('LOWER WEST SIDE', 7257),
 ('MCKINLEY PARK', 1552),
 ('MONTCLARE', 1317),
 ('MORGAN PARK', 3271),
 ('MOUNT GREENWOOD', 2091),
 ('NEAR NORTH SIDE', 3362),
 ('NEAR SOUTH SIDE', 1378),
 ('NEAR WEST SIDE', 7975),
 ('NEW CITY', 7922),
 ('NORTH CENTER', 7541),
 ('NORTH LAWNDALE', 5146),
 ('NORTH PARK', 4210),
 ('NORWOOD PARK', 6469),
 ('OAKLAND', 140),
 ('OHARE', 786),
 ('PORTAGE PARK', 6954),
 ('PULLMAN', 1620),
 ('RIVERDALE', 1547),
 ('ROGERS PARK', 4068),
 ('ROSELAND', 7020),
 ('SOUTH CHICAGO', 4043),
 ('SOUTH DEERING', 1859),
 ('SOUTH LAWNDALE', 14793),
 ('SOUTH SHORE', 4543),
 ('UPTOWN', 4388),
 ('WASHINGTON HEIGHTS', 4006),
 ('WASHINGTON PARK', 2648),
 ('WEST ELSDON', 3700),
 ('WEST ENGLEWOOD', 5946),
 ('WEST GARFIELD PARK', 2622),
 ('WEST LAWN', 4207),
 ('WEST PULLMAN', 3240),
 ('WEST RIDGE', 8197),
 ('WEST TOWN', 9429),
 ('WOODLAWN', 4206)]

In [18]:
%sql SELECT COMMUNITY_AREA_NAME, SUM(COLLEGE_ENROLLMENT) as COLLEGE_ENROLLMENT \
    FROM SCHOOLS \
    GROUP BY COMMUNITY_AREA_NAME \
    order by COLLEGE_ENROLLMENT ASC \
    fetch first 5 rows only

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('OAKLAND', 140),
 ('FULLER PARK', 531),
 ('BURNSIDE', 549),
 ('OHARE', 786),
 ('LOOP', 871)]

In [19]:
##%sql SELECT * FROM SYSCAT.TABLES

In [20]:
%sql SELECT * FROM SYSCAT.COLUMNS WHERE TABNAME = 'CHICAGO_SOCIOECONOMIC_DATA'

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'index', 0, 'SYSIBM  ', 'BIGINT', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '76', '1', 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'CA', 1, 'SYSIBM  ', 'DOUBLE', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '+7.70000000000000E+001', '+2.00000000000000E+000', 9, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'COMMUNITY_AREA_NAME', 2, 'SYSIBM  ', 'CLOB', 1048576, 0, 'OCTETS', 1048576, None, 'Y', 1208, 'SYSIBM', 'IDENTITY', 'Y', 'N', -1, '', '', 64, None, 0, -1, -1, 0, None, None, None, None, None, None, None, None, ' ', 164, 100, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'PERCENT_OF_HOUSING_CROWDED', 3, 'SYSIBM  ', 'DOUBLE', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 56, '+1.52000000000000E+001', '+8.00000000000000E-001', 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'PERCENT_HOUSEHOLDS_BELOW_POVERTY', 4, 'SYSIBM  ', 'DOUBLE', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 68, '+5.12000000000000E+001', '+3.40000000000000E+000', 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'PERCENT_AGED_16_UNEMPLOYED', 5, 'SYSIBM  ', 'DOUBLE', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 67, '+3.46000000000000E+001', '+4.90000000000000E+000', 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'PERCENT_AGED_25_WITHOUT_HIGH_SCHOOL_DIPLOMA', 6, 'SYSIBM  ', 'DOUBLE', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 70, '+5.15000000000000E+001', '+2.60000000000000E+000', 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'PERCENT_AGED_UNDER_18_OR_OVER_64', 7, 'SYSIBM  ', 'DOUBLE', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 67, '+4.49000000000000E+001', '+1.70000000000000E+001', 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'PER_CAPITA_INCOME_', 8, 'SYSIBM  ', 'BIGINT', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '71551', '10402', 9, None, 0, 20, 10, 0, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None),
 ('QMM86575', 'CHICAGO_SOCIOECONOMIC_DATA', 'HARDSHIP_INDEX', 9, 'SYSIBM  ', 'DOUBLE', 8, 0, None, None, None, 'Y', 0, None, None, ' ', ' ', 78, '+9.80000000000000E+001', '+2.00000000000000E+000', 9, None, 0, 20, 10, 1, None, None, None, None, None, None, None, None, ' ', 0, -1, 'N', 'N', ' ', None, 'O', None, -1.0, -1, -1, -1, None, None, 'N', 'N', 'N', -1, -1.0, None, None, 'N', None)]

In [22]:
%sql SELECT CA, HARDSHIP_INDEX FROM CHICAGO_SOCIOECONOMIC_DATA

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(1.0, 39.0),
 (2.0, 46.0),
 (3.0, 20.0),
 (4.0, 17.0),
 (5.0, 6.0),
 (6.0, 5.0),
 (7.0, 2.0),
 (8.0, 1.0),
 (9.0, 8.0),
 (10.0, 21.0),
 (11.0, 25.0),
 (12.0, 11.0),
 (13.0, 33.0),
 (14.0, 53.0),
 (15.0, 35.0),
 (16.0, 34.0),
 (17.0, 28.0),
 (18.0, 50.0),
 (19.0, 70.0),
 (20.0, 71.0),
 (21.0, 42.0),
 (22.0, 23.0),
 (23.0, 85.0),
 (24.0, 10.0),
 (25.0, 73.0),
 (26.0, 92.0),
 (27.0, 83.0),
 (28.0, 15.0),
 (29.0, 87.0),
 (30.0, 96.0),
 (31.0, 76.0),
 (32.0, 3.0),
 (33.0, 7.0),
 (34.0, 82.0),
 (35.0, 47.0),
 (36.0, 78.0),
 (37.0, 97.0),
 (38.0, 57.0),
 (39.0, 26.0),
 (40.0, 88.0),
 (41.0, 14.0),
 (42.0, 58.0),
 (43.0, 55.0),
 (44.0, 60.0),
 (45.0, 41.0),
 (46.0, 75.0),
 (47.0, 79.0),
 (48.0, 38.0),
 (49.0, 52.0),
 (50.0, 51.0),
 (51.0, 65.0),
 (52.0, 64.0),
 (53.0, 62.0),
 (54.0, 98.0),
 (55.0, 44.0),
 (56.0, 32.0),
 (57.0, 67.0),
 (58.0, 84.0),
 (59.0, 61.0),
 (60.0, 43.0),
 (61.0, 91.0),
 (62.0, 69.0),
 (63.0, 93.0),
 (64.0, 29.0),
 (65.0, 56.0),
 (66.0, 80.0),
 (67.0, 89.0),
 (68.0, 94.0),
 (69.0, 66.0),
 (70.0, 37.0),
 (71.0, 74.0),
 (72.0, 12.0),
 (73.0, 48.0),
 (74.0, 16.0),
 (75.0, 30.0),
 (76.0, 24.0),
 (77.0, 19.0),
 (None, None)]

In [23]:
%sql SELECT COMMUNITY_AREA_NUMBER FROM SCHOOLS

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(7,),
 (43,),
 (70,),
 (61,),
 (34,),
 (14,),
 (5,),
 (24,),
 (5,),
 (14,),
 (5,),
 (61,),
 (6,),
 (24,),
 (49,),
 (49,),
 (23,),
 (72,),
 (27,),
 (29,),
 (48,),
 (22,),
 (68,),
 (24,),
 (42,),
 (28,),
 (67,),
 (74,),
 (24,),
 (38,),
 (39,),
 (67,),
 (46,),
 (61,),
 (44,),
 (17,),
 (44,),
 (67,),
 (70,),
 (6,),
 (25,),
 (42,),
 (25,),
 (45,),
 (75,),
 (19,),
 (31,),
 (68,),
 (68,),
 (24,),
 (40,),
 (39,),
 (64,),
 (41,),
 (23,),
 (58,),
 (38,),
 (51,),
 (44,),
 (58,),
 (16,),
 (21,),
 (68,),
 (70,),
 (38,),
 (61,),
 (19,),
 (29,),
 (70,),
 (30,),
 (73,),
 (41,),
 (60,),
 (45,),
 (19,),
 (22,),
 (67,),
 (69,),
 (69,),
 (26,),
 (67,),
 (17,),
 (17,),
 (74,),
 (35,),
 (45,),
 (9,),
 (49,),
 (24,),
 (71,),
 (66,),
 (29,),
 (58,),
 (49,),
 (38,),
 (29,),
 (30,),
 (2,),
 (10,),
 (38,),
 (30,),
 (23,),
 (68,),
 (26,),
 (30,),
 (5,),
 (61,),
 (2,),
 (16,),
 (66,),
 (52,),
 (19,),
 (39,),
 (42,),
 (49,),
 (70,),
 (29,),
 (40,),
 (50,),
 (12,),
 (10,),
 (40,),
 (43,),
 (40,),
 (26,),
 (46,),
 (59,),
 (8,),
 (25,),
 (65,),
 (61,),
 (53,),
 (15,),
 (67,),
 (69,),
 (30,),
 (72,),
 (24,),
 (4,),
 (25,),
 (61,),
 (24,),
 (69,),
 (30,),
 (42,),
 (43,),
 (63,),
 (63,),
 (15,),
 (75,),
 (1,),
 (76,),
 (59,),
 (66,),
 (21,),
 (28,),
 (62,),
 (73,),
 (39,),
 (63,),
 (73,),
 (71,),
 (30,),
 (66,),
 (37,),
 (25,),
 (68,),
 (49,),
 (49,),
 (8,),
 (58,),
 (21,),
 (19,),
 (29,),
 (24,),
 (25,),
 (22,),
 (9,),
 (5,),
 (13,),
 (63,),
 (28,),
 (71,),
 (26,),
 (2,),
 (60,),
 (77,),
 (74,),
 (50,),
 (25,),
 (8,),
 (50,),
 (25,),
 (54,),
 (54,),
 (52,),
 (52,),
 (49,),
 (23,),
 (26,),
 (30,),
 (3,),
 (67,),
 (30,),
 (16,),
 (26,),
 (65,),
 (49,),
 (13,),
 (19,),
 (47,),
 (23,),
 (25,),
 (6,),
 (26,),
 (77,),
 (14,),
 (55,),
 (19,),
 (25,),
 (69,),
 (75,),
 (43,),
 (16,),
 (68,),
 (6,),
 (46,),
 (25,),
 (42,),
 (77,),
 (35,),
 (30,),
 (30,),
 (6,),
 (54,),
 (63,),
 (31,),
 (38,),
 (43,),
 (36,),
 (27,),
 (15,),
 (11,),
 (4,),
 (44,),
 (6,),
 (61,),
 (43,),
 (22,),
 (46,),
 (24,),
 (35,),
 (23,),
 (58,),
 (42,),
 (34,),
 (29,),
 (52,),
 (44,),
 (11,),
 (24,),
 (27,),
 (53,),
 (68,),
 (22,),
 (31,),
 (20,),
 (35,),
 (16,),
 (27,),
 (58,),
 (5,),
 (64,),
 (34,),
 (75,),
 (66,),
 (42,),
 (56,),
 (69,),
 (31,),
 (62,),
 (69,),
 (25,),
 (61,),
 (56,),
 (72,),
 (5,),
 (35,),
 (51,),
 (27,),
 (49,),
 (27,),
 (28,),
 (53,),
 (14,),
 (67,),
 (30,),
 (3,),
 (44,),
 (71,),
 (10,),
 (53,),
 (24,),
 (16,),
 (1,),
 (24,),
 (30,),
 (3,),
 (30,),
 (18,),
 (31,),
 (27,),
 (25,),
 (3,),
 (48,),
 (68,),
 (31,),
 (1,),
 (29,),
 (25,),
 (48,),
 (72,),
 (20,),
 (39,),
 (6,),
 (49,),
 (7,),
 (24,),
 (19,),
 (23,),
 (29,),
 (30,),
 (27,),
 (44,),
 (25,),
 (7,),
 (70,),
 (30,),
 (21,),
 (22,),
 (6,),
 (7,),
 (25,),
 (6,),
 (62,),
 (38,),
 (67,),
 (19,),
 (4,),
 (77,),
 (71,),
 (24,),
 (27,),
 (31,),
 (73,),
 (65,),
 (30,),
 (57,),
 (28,),
 (60,),
 (28,),
 (56,),
 (66,),
 (69,),
 (23,),
 (19,),
 (6,),
 (48,),
 (13,),
 (19,),
 (27,),
 (27,),
 (29,),
 (29,),
 (52,),
 (73,),
 (38,),
 (27,),
 (56,),
 (25,),
 (49,),
 (25,),
 (2,),
 (39,),
 (75,),
 (23,),
 (28,),
 (74,),
 (73,),
 (30,),
 (43,),
 (59,),
 (64,),
 (29,),
 (26,),
 (58,),
 (33,),
 (44,),
 (24,),
 (1,),
 (46,),
 (16,),
 (77,),
 (68,),
 (46,),
 (17,),
 (23,),
 (14,),
 (13,),
 (73,),
 (13,),
 (19,),
 (10,),
 (24,),
 (17,),
 (44,),
 (68,),
 (10,),
 (31,),
 (23,),
 (51,),
 (25,),
 (7,),
 (23,),
 (69,),
 (43,),
 (16,),
 (71,),
 (35,),
 (69,),
 (68,),
 (68,),
 (35,),
 (15,),
 (31,),
 (2,),
 (60,),
 (41,),
 (56,),
 (28,),
 (31,),
 (15,),
 (22,),
 (63,),
 (53,),
 (6,),
 (33,),
 (57,),
 (65,),
 (61,),
 (71,),
 (28,),
 (22,),
 (4,),
 (48,),
 (25,),
 (61,),
 (60,),
 (51,),
 (64,),
 (67,),
 (28,),
 (24,),
 (24,),
 (1,),
 (53,),
 (25,),
 (30,),
 (29,),
 (73,),
 (8,),
 (10,),
 (22,),
 (53,),
 (12,),
 (71,),
 (20,),
 (63,),
 (68,),
 (67,),
 (8,),
 (63,),
 (53,),
 (33,),
 (43,),
 (67,),
 (25,),
 (30,),
 (2,),
 (1,),
 (77,),
 (2,),
 (2,),
 (28,),
 (63,),
 (66,),
 (68,),
 (30,),
 (29,),
 (14,),
 (50,),
 (14,),
 (37,),
 (29,),
 (22,),
 (48,),
 (53,),
 (4,),
 (58,),
 (16,),
 (49,),
 (3,),
 (59,),
 (28,),
 (55,),
 (25,),
 (3,),
 (7,),
 (8,),
 (71,),
 (68,),
 (63,),
 (15,),
 (28,),
 (24,),
 (73,),
 (35,),
 (50,),
 (23,),
 (53,),
 (2,),
 (28,),
 (12,),
 (27,),
 (68,),
 (70,),
 (8,),
 (3,),
 (39,),
 (54,),
 (17,),
 (31,),
 (14,),
 (28,),
 (28,),
 (10,),
 (7,),
 (41,),
 (71,),
 (61,),
 (70,),
 (35,),
 (10,),
 (32,),
 (46,),
 (29,),
 (15,),
 (20,),
 (67,),
 (35,),
 (35,),
 (61,),
 (40,),
 (22,),
 (42,),
 (30,)]

In [25]:
%sql SELECT CA, COMMUNITY_AREA_NAME, HARDSHIP_INDEX FROM CHICAGO_SOCIOECONOMIC_DATA \
    WHERE CA in (select COMMUNITY_AREA_NUMBER FROM SCHOOLS ORDER BY COLLEGE_ENROLLMENT DESC LIMIT 1)

 * ibm_db_sa://qmm86575:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(5.0, 'North Center', 6.0)]